/**
 * Initial (mock) data — loaded into localStorage on first access.
 * Each record automatically gets an `id` and `created_date` from client.js
 * when persisted; here we already include them to have stable relationships.
 *
 * Profiles (role): admin | vendedor_interno | vendedor_externo | tecnico
 */

const now = new Date().toISOString();

export const seedData = {
  User: [
    {
      id: 'u-admin',
      full_name: 'Paulo Do Gera',
      matricula: 'admin',
      plain_password: '123',
      role: 'admin',
      position: 'ADM Master',
      phone: '(11) 99999-0001',
      is_active: true,
      allowed_modules: [],
      created_date: now,
    },
    {
      id: 'u-vint',
      full_name: 'Maria Vendas',
      matricula: 'vint',
      plain_password: '123',
      role: 'vendedor_interno',
      position: 'Vendedora Interna',
      phone: '(11) 99999-0002',
      is_active: true,
      allowed_modules: [],
      created_date: now,
    },
    {
      id: 'u-vext',
      full_name: 'João Campo',
      matricula: 'vext',
      plain_password: '123',
      role: 'vendedor_externo',
      position: 'Vendedor Externo',
      phone: '(11) 99999-0003',
      is_active: true,
      allowed_modules: [],
      created_date: now,
    },
    {
      id: 'u-tec',
      full_name: 'Carlos Técnico',
      matricula: 'tec',
      plain_password: '123',
      role: 'tecnico',
      position: 'Técnico Condominial',
      phone: '(11) 99999-0004',
      is_active: true,
      allowed_modules: [],
      created_date: now,
    },
  ],

  Supplier: [
    {
      id: 's-1',
      name: 'Bombas Brasil Ltda',
      document: '12.345.678/0001-90',
      email: 'contato@bombasbrasil.com.br',
      phone: '(11) 3000-1000',
      contact_person: 'Roberto',
      created_date: now,
    },
    {
      id: 's-2',
      name: 'HidroPeças Distribuidora',
      document: '98.765.432/0001-10',
      email: 'vendas@hidropecas.com.br',
      phone: '(11) 3000-2000',
      contact_person: 'Ana',
      created_date: now,
    },
  ],

  Product: [
    {
      id: 'p-1',
      name: 'Bomba Submersa 1CV',
      sku: 'BS-1CV',
      barcode: '7891000000017',
      category: 'Bombas',
      sale_price: 1250.0,
      stock_quantity: 12,
      min_stock: 5,
      unit: 'un',
      is_active: true,
      created_date: now,
    },
    {
      id: 'p-2',
      name: 'Cloro Granulado 10kg',
      sku: 'CLR-10',
      barcode: '7891000000024',
      category: 'Químicos',
      sale_price: 189.9,
      stock_quantity: 3,
      min_stock: 8,
      unit: 'balde',
      is_active: true,
      created_date: now,
    },
    {
      id: 'p-3',
      name: 'Filtro de Areia FM-40',
      sku: 'FLT-40',
      barcode: '7891000000031',
      category: 'Filtros',
      sale_price: 890.0,
      stock_quantity: 7,
      min_stock: 3,
      unit: 'un',
      is_active: true,
      created_date: now,
    },
    {
      id: 'p-4',
      name: 'Mangueira Sucção 2" (m)',
      sku: 'MNG-2',
      barcode: '7891000000048',
      category: 'Acessórios',
      sale_price: 24.5,
      stock_quantity: 120,
      min_stock: 30,
      unit: 'm',
      is_active: true,
      created_date: now,
    },
  ],

  Client: [
    {
      id: 'c-1',
      name: 'Condomínio Solar das Águas',
      type: 'condominio',
      document: '11.111.111/0001-11',
      email: 'sindico@solardasaguas.com.br',
      phone: '(11) 4000-1000',
      contact_person: 'Síndico Marcos',
      address: 'Rua das Palmeiras',
      address_number: '100',
      neighborhood: 'Jardim Europa',
      city_name: 'São Paulo',
      state: 'SP',
      zip_code: '01000-000',
      validation_status: 'ativo',
      registered_by_role: 'admin',
      next_maintenance_date: '2026-07-01',
      maintenance_approved: true,
      created_date: now,
    },
    {
      id: 'c-2',
      name: 'José da Silva',
      type: 'pessoa_fisica',
      document: '123.456.789-00',
      email: 'jose@email.com',
      phone: '(11) 98888-1234',
      city_name: 'São Paulo',
      state: 'SP',
      validation_status: 'ativo',
      registered_by_role: 'admin',
      created_date: now,
    },
    {
      id: 'c-3',
      name: 'Academia Fit Pool',
      type: 'pessoa_juridica',
      document: '22.222.222/0001-22',
      email: 'contato@fitpool.com.br',
      phone: '(11) 4000-2000',
      contact_person: 'Gerente Paula',
      city_name: 'Guarulhos',
      state: 'SP',
      validation_status: 'aguardando_validacao',
      registered_by_role: 'vendedor_externo',
      created_date: now,
    },
  ],

  Sale: [
    {
      id: 'sale-1',
      type: 'interna',
      seller_id: 'u-vint',
      seller_name: 'Maria Vendas',
      client_id: 'c-2',
      client_name: 'José da Silva',
      items: [
        { product_id: 'p-2', product_name: 'Cloro Granulado 10kg', quantity: 2, unit_price: 189.9, total: 379.8 },
      ],
      total_amount: 379.8,
      total_items: 2,
      payment_method: 'pix',
      status: 'consolidada',
      sale_date: now,
      created_date: now,
    },
    {
      id: 'sale-2',
      type: 'externa',
      seller_id: 'u-vext',
      seller_name: 'João Campo',
      client_id: 'c-1',
      client_name: 'Condomínio Solar das Águas',
      items: [
        { product_id: 'p-1', product_name: 'Bomba Submersa 1CV', quantity: 1, unit_price: 1250.0, total: 1250.0 },
        { product_id: 'p-4', product_name: 'Mangueira Sucção 2" (m)', quantity: 10, unit_price: 24.5, total: 245.0 },
      ],
      total_amount: 1495.0,
      total_items: 11,
      payment_method: 'boleto',
      status: 'pendente_envio',
      sale_date: now,
      created_date: now,
    },
  ],

  ServiceOrder: [
    {
      id: 'os-1',
      type: 'os',
      client_id: 'c-1',
      client_name: 'Condomínio Solar das Águas',
      description: 'Manutenção preventiva do sistema de filtragem',
      assigned_to_id: 'u-tec',
      assigned_to_name: 'Carlos Técnico',
      items_used: [],
      status: 'aguardando_validacao',
      service_value: 450.0,
      payment_status: 'a_receber',
      scheduled_date: '2026-06-10',
      scheduled_time: '09:00',
      created_date: now,
    },
    {
      id: 'os-2',
      type: 'orcamento',
      client_id: 'c-3',
      client_name: 'Academia Fit Pool',
      description: 'Troca de bomba e revisão hidráulica',
      items_used: [],
      status: 'validada',
      service_value: 1800.0,
      payment_status: 'a_receber',
      scheduled_date: '2026-06-12',
      created_date: now,
    },
  ],

  ServiceTask: [
    {
      id: 't-1',
      service_order_id: 'os-1',
      assigned_to_id: 'u-tec',
      assigned_to_name: 'Carlos Técnico',
      client_id: 'c-1',
      client_name: 'Condomínio Solar das Águas',
      description: 'Manutenção preventiva — Solar das Águas',
      status: 'agendado',
      scheduled_date: '2026-06-10',
      scheduled_time: '09:00',
      created_date: now,
    },
  ],

  StockEntry: [
    {
      id: 'se-1',
      product_id: 'p-1',
      product_name: 'Bomba Submersa 1CV',
      supplier_id: 's-1',
      supplier_name: 'Bombas Brasil Ltda',
      quantity: 10,
      unit_cost: 820.0,
      total_cost: 8200.0,
      entry_date: now,
      invoice_number: 'NF-1001',
      created_date: now,
    },
  ],

};

export const ENTITIES = Object.keys(seedData);
